---
- block: # Check and install Docker Compose
  - name: Check if docker compose version {{ docker_compose_install_version }} is installed
    shell: |
      docker-compose --version |
      grep "version {{ docker_compose_install_version }},"
    ignore_errors: true
    register: docker_compose_install_check

  - name: Install python 3 pip
    apt:
      name: python3-pip
      state: present

  - name: Install Docker Compose if not installed
    pip:
      name: docker-compose
    # get_url:
    #   url: "{{ docker_compose_install_url }}"
    #   dest: "{{ docker_compose_install_path }}"
    #   mode: 0755
    #   force: yes
    become: true
    when: docker_compose_install_check.rc != 0

  tags:
    - docker-compose-install
